imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    default_locale:  en
    session:
        storage_id: session.storage.filesystem

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: main
        connections:
            main:
                driver:   pdo_sqlite
                path:     %kernel.cache_dir%/db.sqlite
                charset:  UTF8

        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

security:
    firewalls:
        api:
            http_basic: ~
