_rednose_framework_security:
    resource: "@RednoseFrameworkBundle/Resources/config/routing/security.xml"

_rednose_framework_device:
    resource: "@RednoseFrameworkBundle/Resources/config/routing/device.xml"
    prefix:   /lox_api

libbit_lox:
    resource: "@LibbitLoxBundle/Resources/config/routing.yml"
    prefix:   /

rednose_framework_oauth2_authorize:
    pattern: /oauth2/authorize
    defaults: { _controller: RednoseFrameworkBundle:Authorize:authorize }
    requirements:
        _method: GET|POST

rednose_framework_oauth2_token:
    pattern: /lox_api/oauth2/token
    defaults: { _controller: RednoseFrameworkBundle:Authorize:token }
    requirements:
        _method: GET|POST

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

RednoseCdnBundle:
    resource: '@RednoseCdnBundle/Resources/config/routing/rednose_cdn.xml'
    prefix: /cdn

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
