_rednose_framework_security:
    resource: "@RednoseFrameworkBundle/Resources/config/routing/security.xml"

#_rednose_framework_device:
#    resource: "@RednoseFrameworkBundle/Resources/config/routing/device.xml"
#    prefix:   /lox_api

libbit_lox:
    resource: "@LibbitLoxBundle/Resources/config/routing.yml"
    prefix:   /

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

RednoseComboHandlerBundle:
    resource: "@RednoseComboHandlerBundle/Resources/config/routing.yml"
    prefix: /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
