jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        rednose_frameworkbundle:
            id: rednose_framework.user_manager

    firewalls:
        oauth_token:
            pattern: ^/oauth/v2/token
            security: false

        api:
            pattern: ^/lox_api
            fos_oauth: true
            stateless: true

        public:
            pattern: ^/public
            security: false

        main:
            pattern:    ^/.*
            form_login:
                check_path: /login_check
                login_path: /login
            logout: true
            security: true
            anonymous: true
            switch_user: true

            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/combo, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_SUPER_ADMIN }
        - { path: ^/lox_api, roles: [ IS_AUTHENTICATED_FULLY ] }
        - { path: ^/.*, roles: ROLE_USER }

